image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - createMR

build_project:
    image: node:latest
    stage: build
    script:
        - npm install

test_project:
    image: node:latest
    stage: test
    script:
        - npm test

create_merge_request:
  stage: createMR
  script:
    - 'echo Merge request opened by $GITLAB_USER_NAME'
    - ./commit.sh

