image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - createMR

build_project:
    image: node:latest
    stage: build
    script:
        - npm install

test_project:
    image: node:latest
    stage: test
    script:
        - npm test

create_merge_request:
    before_script: []   # We do not need any setup work, let's remove the global one (if any)
    stage: createMR
    only:
      - /^feature\/*/   # We have a very strict naming convention
    script:
        - HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${PRIVATE_TOKEN} ./commit.sh
