FROM node:7.9

LABEL maintainer="ahoxha.01@gmail.com"

WORKDIR /usr/src/app

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
COPY package.json /usr/src/app/
RUN npm install

COPY . /usr/src/app
COPY commit.sh /usr/bin/
##CMD ["commit.sh"]
EXPOSE 8080

CMD [ "npm", "run", "start"]
